name: Build & Publish image to docker hub
on:
    push:
        branches: 
            - main
        paths:
            Dockerfile

jobs:
    publish_images:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Log in to Docker hub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_TOKEN}}
            - name: Build Docker Image
              run: docker build -t dilycodes/dilycodes:latest .
            - name: Push Docker Image to Docker Hub
              run: docker push dilycodes/dilycodes:latest